# Generated by Django 2.1.2 on 2018-10-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181017_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
